name: Validate with hassfest

on:
  push:
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clear hassfest cache
        run: rm -rf ~/.cache/hassfest || true

      - uses: home-assistant/actions/hassfest@master
